/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested, IsInt } from "class-validator";
import { AppointmentsCreateNestedManyWithoutCustomersItemsInput } from "./AppointmentsCreateNestedManyWithoutCustomersItemsInput";
import { Type } from "class-transformer";
import { ReviewsCreateNestedManyWithoutCustomersItemsInput } from "./ReviewsCreateNestedManyWithoutCustomersItemsInput";

@InputType()
class CustomersCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: () => AppointmentsCreateNestedManyWithoutCustomersItemsInput,
  })
  @ValidateNested()
  @Type(() => AppointmentsCreateNestedManyWithoutCustomersItemsInput)
  @IsOptional()
  @Field(() => AppointmentsCreateNestedManyWithoutCustomersItemsInput, {
    nullable: true,
  })
  appointmentsItems?: AppointmentsCreateNestedManyWithoutCustomersItemsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  avatar?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fullName?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  loyaltyPoints?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  refreshToken?: string | null;

  @ApiProperty({
    required: false,
    type: () => ReviewsCreateNestedManyWithoutCustomersItemsInput,
  })
  @ValidateNested()
  @Type(() => ReviewsCreateNestedManyWithoutCustomersItemsInput)
  @IsOptional()
  @Field(() => ReviewsCreateNestedManyWithoutCustomersItemsInput, {
    nullable: true,
  })
  reviewsItems?: ReviewsCreateNestedManyWithoutCustomersItemsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string | null;
}

export { CustomersCreateInput as CustomersCreateInput };
