/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { AppointmentsUpdateManyWithoutEmployeesItemsInput } from "./AppointmentsUpdateManyWithoutEmployeesItemsInput";
import { Type } from "class-transformer";
import { ReviewsUpdateManyWithoutEmployeesItemsInput } from "./ReviewsUpdateManyWithoutEmployeesItemsInput";
import { StoresWhereUniqueInput } from "../../stores/base/StoresWhereUniqueInput";
import { StoresUpdateManyWithoutEmployeesItemsInput } from "./StoresUpdateManyWithoutEmployeesItemsInput";

@InputType()
class EmployeesUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: () => AppointmentsUpdateManyWithoutEmployeesItemsInput,
  })
  @ValidateNested()
  @Type(() => AppointmentsUpdateManyWithoutEmployeesItemsInput)
  @IsOptional()
  @Field(() => AppointmentsUpdateManyWithoutEmployeesItemsInput, {
    nullable: true,
  })
  appointmentsItems?: AppointmentsUpdateManyWithoutEmployeesItemsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  availability?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  avatar?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fullName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  refreshToken?: string | null;

  @ApiProperty({
    required: false,
    type: () => ReviewsUpdateManyWithoutEmployeesItemsInput,
  })
  @ValidateNested()
  @Type(() => ReviewsUpdateManyWithoutEmployeesItemsInput)
  @IsOptional()
  @Field(() => ReviewsUpdateManyWithoutEmployeesItemsInput, {
    nullable: true,
  })
  reviewsItems?: ReviewsUpdateManyWithoutEmployeesItemsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  role?: string | null;

  @ApiProperty({
    required: false,
    type: () => StoresWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => StoresWhereUniqueInput)
  @IsOptional()
  @Field(() => StoresWhereUniqueInput, {
    nullable: true,
  })
  store?: StoresWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => StoresUpdateManyWithoutEmployeesItemsInput,
  })
  @ValidateNested()
  @Type(() => StoresUpdateManyWithoutEmployeesItemsInput)
  @IsOptional()
  @Field(() => StoresUpdateManyWithoutEmployeesItemsInput, {
    nullable: true,
  })
  storesItems?: StoresUpdateManyWithoutEmployeesItemsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string | null;
}

export { EmployeesUpdateInput as EmployeesUpdateInput };
