/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { EmployeesService } from "../employees.service";
import { EmployeesCreateInput } from "./EmployeesCreateInput";
import { Employees } from "./Employees";
import { EmployeesFindManyArgs } from "./EmployeesFindManyArgs";
import { EmployeesWhereUniqueInput } from "./EmployeesWhereUniqueInput";
import { EmployeesUpdateInput } from "./EmployeesUpdateInput";
import { AppointmentsFindManyArgs } from "../../appointments/base/AppointmentsFindManyArgs";
import { Appointments } from "../../appointments/base/Appointments";
import { AppointmentsWhereUniqueInput } from "../../appointments/base/AppointmentsWhereUniqueInput";
import { ReviewsFindManyArgs } from "../../reviews/base/ReviewsFindManyArgs";
import { Reviews } from "../../reviews/base/Reviews";
import { ReviewsWhereUniqueInput } from "../../reviews/base/ReviewsWhereUniqueInput";
import { StoresFindManyArgs } from "../../stores/base/StoresFindManyArgs";
import { Stores } from "../../stores/base/Stores";
import { StoresWhereUniqueInput } from "../../stores/base/StoresWhereUniqueInput";

export class EmployeesControllerBase {
  constructor(protected readonly service: EmployeesService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Employees })
  async createEmployees(
    @common.Body() data: EmployeesCreateInput
  ): Promise<Employees> {
    return await this.service.createEmployees({
      data: {
        ...data,

        store: data.store
          ? {
              connect: data.store,
            }
          : undefined,
      },
      select: {
        address: true,
        availability: true,
        avatar: true,
        createdAt: true,
        email: true,
        fullName: true,
        id: true,
        password: true,
        phone: true,
        refreshToken: true,
        role: true,

        store: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Employees] })
  @ApiNestedQuery(EmployeesFindManyArgs)
  async employeesItems(@common.Req() request: Request): Promise<Employees[]> {
    const args = plainToClass(EmployeesFindManyArgs, request.query);
    return this.service.employeesItems({
      ...args,
      select: {
        address: true,
        availability: true,
        avatar: true,
        createdAt: true,
        email: true,
        fullName: true,
        id: true,
        password: true,
        phone: true,
        refreshToken: true,
        role: true,

        store: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Employees })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async employees(
    @common.Param() params: EmployeesWhereUniqueInput
  ): Promise<Employees | null> {
    const result = await this.service.employees({
      where: params,
      select: {
        address: true,
        availability: true,
        avatar: true,
        createdAt: true,
        email: true,
        fullName: true,
        id: true,
        password: true,
        phone: true,
        refreshToken: true,
        role: true,

        store: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Employees })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateEmployees(
    @common.Param() params: EmployeesWhereUniqueInput,
    @common.Body() data: EmployeesUpdateInput
  ): Promise<Employees | null> {
    try {
      return await this.service.updateEmployees({
        where: params,
        data: {
          ...data,

          store: data.store
            ? {
                connect: data.store,
              }
            : undefined,
        },
        select: {
          address: true,
          availability: true,
          avatar: true,
          createdAt: true,
          email: true,
          fullName: true,
          id: true,
          password: true,
          phone: true,
          refreshToken: true,
          role: true,

          store: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Employees })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteEmployees(
    @common.Param() params: EmployeesWhereUniqueInput
  ): Promise<Employees | null> {
    try {
      return await this.service.deleteEmployees({
        where: params,
        select: {
          address: true,
          availability: true,
          avatar: true,
          createdAt: true,
          email: true,
          fullName: true,
          id: true,
          password: true,
          phone: true,
          refreshToken: true,
          role: true,

          store: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/appointmentsItems")
  @ApiNestedQuery(AppointmentsFindManyArgs)
  async findAppointmentsItems(
    @common.Req() request: Request,
    @common.Param() params: EmployeesWhereUniqueInput
  ): Promise<Appointments[]> {
    const query = plainToClass(AppointmentsFindManyArgs, request.query);
    const results = await this.service.findAppointmentsItems(params.id, {
      ...query,
      select: {
        appointmentTime: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        employee: {
          select: {
            id: true,
          },
        },

        id: true,

        service: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/appointmentsItems")
  async connectAppointmentsItems(
    @common.Param() params: EmployeesWhereUniqueInput,
    @common.Body() body: AppointmentsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appointmentsItems: {
        connect: body,
      },
    };
    await this.service.updateEmployees({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/appointmentsItems")
  async updateAppointmentsItems(
    @common.Param() params: EmployeesWhereUniqueInput,
    @common.Body() body: AppointmentsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appointmentsItems: {
        set: body,
      },
    };
    await this.service.updateEmployees({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/appointmentsItems")
  async disconnectAppointmentsItems(
    @common.Param() params: EmployeesWhereUniqueInput,
    @common.Body() body: AppointmentsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appointmentsItems: {
        disconnect: body,
      },
    };
    await this.service.updateEmployees({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/reviewsItems")
  @ApiNestedQuery(ReviewsFindManyArgs)
  async findReviewsItems(
    @common.Req() request: Request,
    @common.Param() params: EmployeesWhereUniqueInput
  ): Promise<Reviews[]> {
    const query = plainToClass(ReviewsFindManyArgs, request.query);
    const results = await this.service.findReviewsItems(params.id, {
      ...query,
      select: {
        comments: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        employee: {
          select: {
            id: true,
          },
        },

        id: true,
        rating: true,

        service: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/reviewsItems")
  async connectReviewsItems(
    @common.Param() params: EmployeesWhereUniqueInput,
    @common.Body() body: ReviewsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reviewsItems: {
        connect: body,
      },
    };
    await this.service.updateEmployees({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/reviewsItems")
  async updateReviewsItems(
    @common.Param() params: EmployeesWhereUniqueInput,
    @common.Body() body: ReviewsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reviewsItems: {
        set: body,
      },
    };
    await this.service.updateEmployees({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/reviewsItems")
  async disconnectReviewsItems(
    @common.Param() params: EmployeesWhereUniqueInput,
    @common.Body() body: ReviewsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reviewsItems: {
        disconnect: body,
      },
    };
    await this.service.updateEmployees({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/storesItems")
  @ApiNestedQuery(StoresFindManyArgs)
  async findStoresItems(
    @common.Req() request: Request,
    @common.Param() params: EmployeesWhereUniqueInput
  ): Promise<Stores[]> {
    const query = plainToClass(StoresFindManyArgs, request.query);
    const results = await this.service.findStoresItems(params.id, {
      ...query,
      select: {
        address: true,
        createdAt: true,
        email: true,

        employees: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,
        phone: true,

        services: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/storesItems")
  async connectStoresItems(
    @common.Param() params: EmployeesWhereUniqueInput,
    @common.Body() body: StoresWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      storesItems: {
        connect: body,
      },
    };
    await this.service.updateEmployees({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/storesItems")
  async updateStoresItems(
    @common.Param() params: EmployeesWhereUniqueInput,
    @common.Body() body: StoresWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      storesItems: {
        set: body,
      },
    };
    await this.service.updateEmployees({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/storesItems")
  async disconnectStoresItems(
    @common.Param() params: EmployeesWhereUniqueInput,
    @common.Body() body: StoresWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      storesItems: {
        disconnect: body,
      },
    };
    await this.service.updateEmployees({
      where: params,
      data,
      select: { id: true },
    });
  }
}
