/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ServicesService } from "../services.service";
import { ServicesCreateInput } from "./ServicesCreateInput";
import { Services } from "./Services";
import { ServicesFindManyArgs } from "./ServicesFindManyArgs";
import { ServicesWhereUniqueInput } from "./ServicesWhereUniqueInput";
import { ServicesUpdateInput } from "./ServicesUpdateInput";
import { AppointmentsFindManyArgs } from "../../appointments/base/AppointmentsFindManyArgs";
import { Appointments } from "../../appointments/base/Appointments";
import { AppointmentsWhereUniqueInput } from "../../appointments/base/AppointmentsWhereUniqueInput";
import { ReviewsFindManyArgs } from "../../reviews/base/ReviewsFindManyArgs";
import { Reviews } from "../../reviews/base/Reviews";
import { ReviewsWhereUniqueInput } from "../../reviews/base/ReviewsWhereUniqueInput";
import { StoresFindManyArgs } from "../../stores/base/StoresFindManyArgs";
import { Stores } from "../../stores/base/Stores";
import { StoresWhereUniqueInput } from "../../stores/base/StoresWhereUniqueInput";

export class ServicesControllerBase {
  constructor(protected readonly service: ServicesService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Services })
  async createServices(
    @common.Body() data: ServicesCreateInput
  ): Promise<Services> {
    return await this.service.createServices({
      data: {
        ...data,

        store: data.store
          ? {
              connect: data.store,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        description: true,
        duration: true,
        id: true,
        price: true,
        serviceName: true,

        store: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Services] })
  @ApiNestedQuery(ServicesFindManyArgs)
  async servicesItems(@common.Req() request: Request): Promise<Services[]> {
    const args = plainToClass(ServicesFindManyArgs, request.query);
    return this.service.servicesItems({
      ...args,
      select: {
        createdAt: true,
        description: true,
        duration: true,
        id: true,
        price: true,
        serviceName: true,

        store: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Services })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async services(
    @common.Param() params: ServicesWhereUniqueInput
  ): Promise<Services | null> {
    const result = await this.service.services({
      where: params,
      select: {
        createdAt: true,
        description: true,
        duration: true,
        id: true,
        price: true,
        serviceName: true,

        store: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Services })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateServices(
    @common.Param() params: ServicesWhereUniqueInput,
    @common.Body() data: ServicesUpdateInput
  ): Promise<Services | null> {
    try {
      return await this.service.updateServices({
        where: params,
        data: {
          ...data,

          store: data.store
            ? {
                connect: data.store,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          description: true,
          duration: true,
          id: true,
          price: true,
          serviceName: true,

          store: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Services })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteServices(
    @common.Param() params: ServicesWhereUniqueInput
  ): Promise<Services | null> {
    try {
      return await this.service.deleteServices({
        where: params,
        select: {
          createdAt: true,
          description: true,
          duration: true,
          id: true,
          price: true,
          serviceName: true,

          store: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/appointmentsItems")
  @ApiNestedQuery(AppointmentsFindManyArgs)
  async findAppointmentsItems(
    @common.Req() request: Request,
    @common.Param() params: ServicesWhereUniqueInput
  ): Promise<Appointments[]> {
    const query = plainToClass(AppointmentsFindManyArgs, request.query);
    const results = await this.service.findAppointmentsItems(params.id, {
      ...query,
      select: {
        appointmentTime: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        employee: {
          select: {
            id: true,
          },
        },

        id: true,

        service: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/appointmentsItems")
  async connectAppointmentsItems(
    @common.Param() params: ServicesWhereUniqueInput,
    @common.Body() body: AppointmentsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appointmentsItems: {
        connect: body,
      },
    };
    await this.service.updateServices({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/appointmentsItems")
  async updateAppointmentsItems(
    @common.Param() params: ServicesWhereUniqueInput,
    @common.Body() body: AppointmentsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appointmentsItems: {
        set: body,
      },
    };
    await this.service.updateServices({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/appointmentsItems")
  async disconnectAppointmentsItems(
    @common.Param() params: ServicesWhereUniqueInput,
    @common.Body() body: AppointmentsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appointmentsItems: {
        disconnect: body,
      },
    };
    await this.service.updateServices({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/reviewsItems")
  @ApiNestedQuery(ReviewsFindManyArgs)
  async findReviewsItems(
    @common.Req() request: Request,
    @common.Param() params: ServicesWhereUniqueInput
  ): Promise<Reviews[]> {
    const query = plainToClass(ReviewsFindManyArgs, request.query);
    const results = await this.service.findReviewsItems(params.id, {
      ...query,
      select: {
        comments: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        employee: {
          select: {
            id: true,
          },
        },

        id: true,
        rating: true,

        service: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/reviewsItems")
  async connectReviewsItems(
    @common.Param() params: ServicesWhereUniqueInput,
    @common.Body() body: ReviewsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reviewsItems: {
        connect: body,
      },
    };
    await this.service.updateServices({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/reviewsItems")
  async updateReviewsItems(
    @common.Param() params: ServicesWhereUniqueInput,
    @common.Body() body: ReviewsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reviewsItems: {
        set: body,
      },
    };
    await this.service.updateServices({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/reviewsItems")
  async disconnectReviewsItems(
    @common.Param() params: ServicesWhereUniqueInput,
    @common.Body() body: ReviewsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reviewsItems: {
        disconnect: body,
      },
    };
    await this.service.updateServices({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/storesItems")
  @ApiNestedQuery(StoresFindManyArgs)
  async findStoresItems(
    @common.Req() request: Request,
    @common.Param() params: ServicesWhereUniqueInput
  ): Promise<Stores[]> {
    const query = plainToClass(StoresFindManyArgs, request.query);
    const results = await this.service.findStoresItems(params.id, {
      ...query,
      select: {
        address: true,
        createdAt: true,
        email: true,

        employees: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,
        phone: true,

        services: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/storesItems")
  async connectStoresItems(
    @common.Param() params: ServicesWhereUniqueInput,
    @common.Body() body: StoresWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      storesItems: {
        connect: body,
      },
    };
    await this.service.updateServices({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/storesItems")
  async updateStoresItems(
    @common.Param() params: ServicesWhereUniqueInput,
    @common.Body() body: StoresWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      storesItems: {
        set: body,
      },
    };
    await this.service.updateServices({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/storesItems")
  async disconnectStoresItems(
    @common.Param() params: ServicesWhereUniqueInput,
    @common.Body() body: StoresWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      storesItems: {
        disconnect: body,
      },
    };
    await this.service.updateServices({
      where: params,
      data,
      select: { id: true },
    });
  }
}
