/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { StoresService } from "../stores.service";
import { StoresCreateInput } from "./StoresCreateInput";
import { Stores } from "./Stores";
import { StoresFindManyArgs } from "./StoresFindManyArgs";
import { StoresWhereUniqueInput } from "./StoresWhereUniqueInput";
import { StoresUpdateInput } from "./StoresUpdateInput";
import { EmployeesFindManyArgs } from "../../employees/base/EmployeesFindManyArgs";
import { Employees } from "../../employees/base/Employees";
import { EmployeesWhereUniqueInput } from "../../employees/base/EmployeesWhereUniqueInput";
import { ServicesFindManyArgs } from "../../services/base/ServicesFindManyArgs";
import { Services } from "../../services/base/Services";
import { ServicesWhereUniqueInput } from "../../services/base/ServicesWhereUniqueInput";

export class StoresControllerBase {
  constructor(protected readonly service: StoresService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Stores })
  async createStores(@common.Body() data: StoresCreateInput): Promise<Stores> {
    return await this.service.createStores({
      data: {
        ...data,

        employees: data.employees
          ? {
              connect: data.employees,
            }
          : undefined,

        services: data.services
          ? {
              connect: data.services,
            }
          : undefined,
      },
      select: {
        address: true,
        createdAt: true,
        email: true,

        employees: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,
        phone: true,

        services: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Stores] })
  @ApiNestedQuery(StoresFindManyArgs)
  async storesItems(@common.Req() request: Request): Promise<Stores[]> {
    const args = plainToClass(StoresFindManyArgs, request.query);
    return this.service.storesItems({
      ...args,
      select: {
        address: true,
        createdAt: true,
        email: true,

        employees: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,
        phone: true,

        services: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Stores })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async stores(
    @common.Param() params: StoresWhereUniqueInput
  ): Promise<Stores | null> {
    const result = await this.service.stores({
      where: params,
      select: {
        address: true,
        createdAt: true,
        email: true,

        employees: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,
        phone: true,

        services: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Stores })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateStores(
    @common.Param() params: StoresWhereUniqueInput,
    @common.Body() data: StoresUpdateInput
  ): Promise<Stores | null> {
    try {
      return await this.service.updateStores({
        where: params,
        data: {
          ...data,

          employees: data.employees
            ? {
                connect: data.employees,
              }
            : undefined,

          services: data.services
            ? {
                connect: data.services,
              }
            : undefined,
        },
        select: {
          address: true,
          createdAt: true,
          email: true,

          employees: {
            select: {
              id: true,
            },
          },

          id: true,
          name: true,
          phone: true,

          services: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Stores })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteStores(
    @common.Param() params: StoresWhereUniqueInput
  ): Promise<Stores | null> {
    try {
      return await this.service.deleteStores({
        where: params,
        select: {
          address: true,
          createdAt: true,
          email: true,

          employees: {
            select: {
              id: true,
            },
          },

          id: true,
          name: true,
          phone: true,

          services: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/employeesItems")
  @ApiNestedQuery(EmployeesFindManyArgs)
  async findEmployeesItems(
    @common.Req() request: Request,
    @common.Param() params: StoresWhereUniqueInput
  ): Promise<Employees[]> {
    const query = plainToClass(EmployeesFindManyArgs, request.query);
    const results = await this.service.findEmployeesItems(params.id, {
      ...query,
      select: {
        address: true,
        availability: true,
        avatar: true,
        createdAt: true,
        email: true,
        fullName: true,
        id: true,
        password: true,
        phone: true,
        refreshToken: true,
        role: true,

        store: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        username: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/employeesItems")
  async connectEmployeesItems(
    @common.Param() params: StoresWhereUniqueInput,
    @common.Body() body: EmployeesWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      employeesItems: {
        connect: body,
      },
    };
    await this.service.updateStores({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/employeesItems")
  async updateEmployeesItems(
    @common.Param() params: StoresWhereUniqueInput,
    @common.Body() body: EmployeesWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      employeesItems: {
        set: body,
      },
    };
    await this.service.updateStores({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/employeesItems")
  async disconnectEmployeesItems(
    @common.Param() params: StoresWhereUniqueInput,
    @common.Body() body: EmployeesWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      employeesItems: {
        disconnect: body,
      },
    };
    await this.service.updateStores({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/servicesItems")
  @ApiNestedQuery(ServicesFindManyArgs)
  async findServicesItems(
    @common.Req() request: Request,
    @common.Param() params: StoresWhereUniqueInput
  ): Promise<Services[]> {
    const query = plainToClass(ServicesFindManyArgs, request.query);
    const results = await this.service.findServicesItems(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        duration: true,
        id: true,
        price: true,
        serviceName: true,

        store: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/servicesItems")
  async connectServicesItems(
    @common.Param() params: StoresWhereUniqueInput,
    @common.Body() body: ServicesWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      servicesItems: {
        connect: body,
      },
    };
    await this.service.updateStores({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/servicesItems")
  async updateServicesItems(
    @common.Param() params: StoresWhereUniqueInput,
    @common.Body() body: ServicesWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      servicesItems: {
        set: body,
      },
    };
    await this.service.updateStores({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/servicesItems")
  async disconnectServicesItems(
    @common.Param() params: StoresWhereUniqueInput,
    @common.Body() body: ServicesWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      servicesItems: {
        disconnect: body,
      },
    };
    await this.service.updateStores({
      where: params,
      data,
      select: { id: true },
    });
  }
}
